<?php

namespace Neralind\TagBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

  /**
   * Get a tag by its ID or its principal word slug
   * @param mixed $idOrSlug
   * @return NeralindTagBundle:Tag
   */
  public function find($idOrSlug) {
    if (is_numeric($idOrSlug)) {
      return parent::find($idOrSlug);
    } else {
      return $this->findOneBySlug($idOrSlug);
    }
  }

  /**
   * Get a tag by its principal word slug
   * @param string $slug
   * @return NeralindTagbundle:Tag
   */
  public function findOneBySlug($slug) {
    $query = $this->getEntityManager()
            ->createQuery('SELECT tag FROM NeralindTagBundle:Tag tag JOIN tag.principalWord word WHERE word.slug = :slug')
            ->setParameter('slug', $slug);

    return $query->getSingleResult();
  }

  public function search($q) {
    try {
      $result = $this->find($q);
      return new ArrayCollection(array($result));
    } catch (\Doctrine\ORM\NoResultException $e) { 
      $query = $this->getEntityManager()
              ->createQuery('SELECT tag FROM NeralindTagBundle:Tag tag JOIN tag.principalWord word WHERE word.slug LIKE :slug')
              ->setParameter('slug', "%$q%");

      return $query->getResult();
    }
  }

}
