<?php

namespace Neralind\TagBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

  /*===============================
  =            PRIVATE            =
  ===============================*/
  
  private function createQuery() {
    return $this->_em->createQueryBuilder()
    ->select('tag')
    ->from('NeralindTagBundle:Tag', 'tag')
    ->join('tag.principalWord', 'word');
  }
  
  private function getPaginator($q, $page = 1, $nbByPage = 10) {
    return new Paginator(
      $q->setFirstResult(($page - 1) * $nbByPage)
      ->setMaxResults($nbByPage));
  }

  /*==============================
  =            PUBLIC            =
  ==============================*/

  /**
   * Get a tag by its ID or its principal word slug
   * @param mixed $idOrSlug
   * @return NeralindTagBundle:Tag
   */
  public function find($idOrSlug) {
    if (is_numeric($idOrSlug)) {
      return parent::find($idOrSlug);
    } else {
      return $this->findOneBySlug($idOrSlug);
    }
  }

  /**
   * Get a tag by its principal word slug
   * @param string $slug
   * @return NeralindTagbundle:Tag
   */
  public function findOneBySlug($slug) {
    $query = $this->getEntityManager()
    ->createQuery('SELECT tag FROM NeralindTagBundle:Tag tag JOIN tag.principalWord word WHERE word.slug = :slug')
    ->setParameter('slug', $slug);

    return $query->getSingleResult();
  }

  public function search($q) {
    try {
      $result = $this->find($q);
      return new ArrayCollection(array($result));
    } catch (\Doctrine\ORM\NoResultException $e) { 
      $query = $this->getEntityManager()
      ->createQuery('SELECT tag FROM NeralindTagBundle:Tag tag JOIN tag.principalWord word WHERE word.slug LIKE :slug')
      ->setParameter('slug', "%$q%");

      return $query->getResult();
    }
  }


  public function findAllPaginator($page = 1, $nbByPage = 10) {
    return $this->getPaginator($this->createQuery(), $page, $nbByPage);
  }

}
