<?php

namespace Neralind\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceVideoRepository extends EntityRepository
{
}
