<?php

namespace Neralind\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceVersionRepository extends EntityRepository
{
}
